[package]
name = "aramuk-web"
version = "0.1.0"
authors = ["Aditesh Kumar <27091329+aramuk@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"